name: Deploy to FTP

on:
  push:
    branches:
      - main  # ここで指定したブランチにpushされたときに実行されます

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv .venv
        . .venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install mkdocs
      run: |
        pip install mkdocs

    - name: Build
      run: |
        mkdocs --version  # mkdocsが正しくインストールされているか確認
        mkdocs build

    - name: Upload to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: 'site'
        server-dir: ${{ secrets.FTP_REMOTE_DIR }}
