name: Deploy to FTP

on:
  push:
    branches:
      - main  # ここで指定したブランチにpushされたときに実行されます

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install mkdocs

    - name: Build the site
      run: |
        source .venv/bin/activate
        mkdocs build

    - name: Upload to FTP server
      uses: sebastianpopp/ftp-action@v1.1.1
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: 'site'
        remote-dir: '${{ secrets.FTP_REMOTE_DIR }}'